version: '3'

services:
  client:
    restart: always
    build:
      context: src/client/
    volumes:
      - ./src/client/src:/var/app/src
    ports:
      - 3000:3000
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpw
      MYSQL_DATABASE: example-db
      MYSQL_USER: example-user
      MYSQL_PASSWORD: password
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./src/db/migrations:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
  server:
    restart: always
    build:
      context: src/server/
    volumes:
      - ./src/server:/var/app
    ports:
      - 4000:4000
    depends_on:
      - "db"
    environment:
      MYSQL_HOST: db
      MYSQL_DATABASE: example-db
      MYSQL_USER: example-user
      MYSQL_PASSWORD: password
      MYSQL_PORT: 3306
