INSERT INTO `people` (`id`, `name`, `img_url`, `location`)
VALUES
  (1, "Vinny Balaison", "https://robohash.org/avoluptatesut.jpg?size=64x64&set=set1", "Batanamang"),
  (2, "Rourke Luckin", "https://robohash.org/utquamreiciendis.jpg?size=64x64&set=set1", "Iguig"),
  (3, "Brianna McElree", "https://robohash.org/omnisbeataeest.jpg?size=64x64&set=set1", "Formiga"),
  (4, "Cindra Philip", "https://robohash.org/quasiidenim.jpg?size=64x64&set=set1", "Tatariv"),
  (5, "Monah Lattie", "https://robohash.org/quasiinquo.jpg?size=64x64&set=set1", "Heping"),
  (6, "Fowler Clapison", "https://robohash.org/aliquamsuscipitillum.jpg?size=64x64&set=set1", "Mekele"),
  (7, "Maryanna Beddow", "https://robohash.org/rerumautest.jpg?size=64x64&set=set1", "Tromsø"),
  (8, "Astrid Manders", "https://robohash.org/enimaperiamculpa.jpg?size=64x64&set=set1", "Hashaat"),
  (9, "Catherin Jerratsch", "https://robohash.org/dignissimosdoloremofficia.jpg?size=64x64&set=set1", "Fu’an"),
  (10, "Jaimie Vobes", "https://robohash.org/minimasuntnatus.jpg?size=64x64&set=set1", "Kotor"),
  (11, "Barnabas O'Downe", "https://robohash.org/rerumquisaut.jpg?size=64x64&set=set1", "Pingshan"),
  (12, "Nickolai Diaper", "https://robohash.org/explicaboconsecteturcorrupti.jpg?size=64x64&set=set1", "Koh Kong"),
  (13, "Leonid Kleinstern", "https://robohash.org/liberoporroquam.jpg?size=64x64&set=set1", "Kurungannyawa"),
  (14, "Osborne Burdas", "https://robohash.org/harumvoluptatevoluptatem.jpg?size=64x64&set=set1", "Lyon"),
  (15, "Alissa Ghost", "https://robohash.org/laudantiumidrerum.jpg?size=64x64&set=set1", "Garanhuns"),
  (16, "Cad Emmet", "https://robohash.org/excepturiexercitationemvoluptatem.jpg?size=64x64&set=set1", "Lianghe"),
  (17, "Noak Mouatt", "https://robohash.org/delenitiquodoloribus.jpg?size=64x64&set=set1", "Xundian"),
  (18, "Colette McBrearty", "https://robohash.org/addelectusrecusandae.jpg?size=64x64&set=set1", "Kumberg"),
  (19, "Morse Jenney", "https://robohash.org/utenimrepellendus.jpg?size=64x64&set=set1", "Juḩr ad Dīk"),
  (20, "Miguelita Iacovone", "https://robohash.org/utexsimilique.jpg?size=64x64&set=set1", "Dikhil"),
  (21, "Vivia Frank", "https://robohash.org/sedaspernaturquaerat.jpg?size=64x64&set=set1", "Uppsala"),
  (22, "Gardy Leyre", "https://robohash.org/delenitidoloremrepudiandae.jpg?size=64x64&set=set1", "Chashnikovo"),
  (23, "Mona Cranny", "https://robohash.org/idquiadolorum.jpg?size=64x64&set=set1", "Mahalapye"),
  (24, "Cece Kerner", "https://robohash.org/etveniamratione.jpg?size=64x64&set=set1", "Wangping"),
  (25, "Boony Haighton", "https://robohash.org/eumetquisquam.jpg?size=64x64&set=set1", "Muheza"),
  (26, "Myrilla Napier", "https://robohash.org/sunthicet.jpg?size=64x64&set=set1", "Ibrā’"),
  (27, "Livvie Carreck", "https://robohash.org/quisutcupiditate.jpg?size=64x64&set=set1", "Pepayan"),
  (28, "Hunt Ring", "https://robohash.org/ducimusetab.jpg?size=64x64&set=set1", "Ganjun"),
  (29, "Wandis Jouhan", "https://robohash.org/eiusdistinctioquasi.jpg?size=64x64&set=set1", "Ţūlkarm"),
  (30, "Corly Cossans", "https://robohash.org/doloribusasperioresid.jpg?size=64x64&set=set1", "Firminy"),
  (31, "Stephanie Mc Gorley", "https://robohash.org/explicabodolorevoluptatem.jpg?size=64x64&set=set1", "Riachão das Neves"),
  (32, "Rubin Bondy", "https://robohash.org/quaenobiscorporis.jpg?size=64x64&set=set1", "Boršice"),
  (33, "Baldwin Pranger", "https://robohash.org/odiovoluptatemcum.jpg?size=64x64&set=set1", "Yanaoca"),
  (34, "Constanta Guyon", "https://robohash.org/doloribusquifugit.jpg?size=64x64&set=set1", "Mang’it Shahri"),
  (35, "Vickie Valler", "https://robohash.org/similiquequiadoloremque.jpg?size=64x64&set=set1", "Tournan-en-Brie"),
  (36, "Hermina Oldland", "https://robohash.org/nobisnatusquisquam.jpg?size=64x64&set=set1", "La Soledad"),
  (37, "Aurel Thomasset", "https://robohash.org/quiasuscipitaut.jpg?size=64x64&set=set1", "Maisons-Alfort"),
  (38, "Joanne Klimek", "https://robohash.org/faceredeseruntofficia.jpg?size=64x64&set=set1", "Xitan"),
  (39, "Terra Wigfield", "https://robohash.org/quiaexrepudiandae.jpg?size=64x64&set=set1", "Tateyama"),
  (40, "Enrika Zmitrichenko", "https://robohash.org/nequepossimusfacere.jpg?size=64x64&set=set1", "Sapol"),
  (41, "Tamara Marcroft", "https://robohash.org/voluptatemquaeratnobis.jpg?size=64x64&set=set1", "Ningyang"),
  (42, "Carly Tenman", "https://robohash.org/debitisvoluptatibuslaudantium.jpg?size=64x64&set=set1", "Saint-Marcellin"),
  (43, "Gerrie Abys", "https://robohash.org/autquasivoluptatibus.jpg?size=64x64&set=set1", "Liudaogou"),
  (44, "Ursuline Stammer", "https://robohash.org/quopossimussit.jpg?size=64x64&set=set1", "Sumberejo"),
  (45, "Ginnie Sappson", "https://robohash.org/totamestnam.jpg?size=64x64&set=set1", "Camden"),
  (46, "Theo Thorn", "https://robohash.org/doloremquiaea.jpg?size=64x64&set=set1", "Sidomulyo"),
  (47, "Shanon Hintze", "https://robohash.org/consequaturfugiatcumque.jpg?size=64x64&set=set1", "Brive-la-Gaillarde"),
  (48, "Dido Bresson", "https://robohash.org/quamtotamdolorem.jpg?size=64x64&set=set1", "Shuangqiaoping"),
  (49, "Iolanthe Norcutt", "https://robohash.org/errorrerummollitia.jpg?size=64x64&set=set1", "Florencia"),
  (50, "Kimball Climance", "https://robohash.org/consequunturnecessitatibussit.jpg?size=64x64&set=set1", "Talayan"),
  (51, "Sonny Davidow", "https://robohash.org/nobisculpanostrum.jpg?size=64x64&set=set1", "Huzhen"),
  (52, "Tanitansy Duthie", "https://robohash.org/etdoloremaccusamus.jpg?size=64x64&set=set1", "Mella"),
  (53, "Humfrid Locard", "https://robohash.org/nullapraesentiumnon.jpg?size=64x64&set=set1", "Caromatan"),
  (54, "Elnora Kingsnoad", "https://robohash.org/esseestnatus.jpg?size=64x64&set=set1", "Orodara"),
  (55, "Juliane Leedal", "https://robohash.org/eosvoluptasdignissimos.jpg?size=64x64&set=set1", "Uppsala"),
  (56, "Torey Lipsett", "https://robohash.org/etnisisint.jpg?size=64x64&set=set1", "Valinhos"),
  (57, "Cordi Helliwell", "https://robohash.org/velitconsequaturvoluptatibus.jpg?size=64x64&set=set1", "Shanggu"),
  (58, "Fletch Wemes", "https://robohash.org/exercitationemnoneveniet.jpg?size=64x64&set=set1", "Zhoupi"),
  (59, "Kat Rubi", "https://robohash.org/quosconsequaturnon.jpg?size=64x64&set=set1", "Colonia Yguazú"),
  (60, "Margaret Hartshorn", "https://robohash.org/laboriosamvitaesit.jpg?size=64x64&set=set1", "Mthatha"),
  (61, "Sib Paulat", "https://robohash.org/magnamvoluptatemillo.jpg?size=64x64&set=set1", "Verba"),
  (62, "Farrell Kiledal", "https://robohash.org/ututaut.jpg?size=64x64&set=set1", "Biguo"),
  (63, "Josi Klaaasen", "https://robohash.org/quiseumeos.jpg?size=64x64&set=set1", "Tomsk"),
  (64, "Sydney Bleasdale", "https://robohash.org/voluptatemlaborequi.jpg?size=64x64&set=set1", "Yauca"),
  (65, "Jacquette Gegg", "https://robohash.org/solutaautemtempore.jpg?size=64x64&set=set1", "Wanbu"),
  (66, "Garik McGuckin", "https://robohash.org/repudiandaedistinctioeum.jpg?size=64x64&set=set1", "Pridonskoy"),
  (67, "Charla Paula", "https://robohash.org/velitquasialias.jpg?size=64x64&set=set1", "København"),
  (68, "Price Lanfranchi", "https://robohash.org/eosmodiest.jpg?size=64x64&set=set1", "Grytviken"),
  (69, "Dunn Kaaskooper", "https://robohash.org/esteumnumquam.jpg?size=64x64&set=set1", "El Rosario"),
  (70, "Audrye Richardes", "https://robohash.org/officiisabaut.jpg?size=64x64&set=set1", "Tonota"),
  (71, "Nikoletta Baylay", "https://robohash.org/doloreseaipsum.jpg?size=64x64&set=set1", "Krasnystaw"),
  (72, "Silvan Boxhall", "https://robohash.org/voluptatescorruptiet.jpg?size=64x64&set=set1", "Lendan"),
  (73, "Hermina Shutte", "https://robohash.org/doloribusnihilatque.jpg?size=64x64&set=set1", "Yasenskaya"),
  (74, "Carrissa Hugenin", "https://robohash.org/sitvoluptatumeius.jpg?size=64x64&set=set1", "Dębe Wielkie"),
  (75, "Pollyanna Batterham", "https://robohash.org/suntexcepturinihil.jpg?size=64x64&set=set1", "Kaeng Khoi"),
  (76, "Keary Bengal", "https://robohash.org/necessitatibussaepeeveniet.jpg?size=64x64&set=set1", "Chikeng"),
  (77, "Ruy O'Gormally", "https://robohash.org/liberomodiet.jpg?size=64x64&set=set1", "Saba Yoi"),
  (78, "Domenic Bransgrove", "https://robohash.org/ametisteofficia.jpg?size=64x64&set=set1", "Salanegara"),
  (79, "Monti Sunner", "https://robohash.org/quiaestsuscipit.jpg?size=64x64&set=set1", "Nanzhao"),
  (80, "Juieta Blain", "https://robohash.org/rationelaborumut.jpg?size=64x64&set=set1", "Sypniewo"),
  (81, "Paulie Oller", "https://robohash.org/liberoquiveniam.jpg?size=64x64&set=set1", "Ḩājī Khēl"),
  (82, "Alyss Tankin", "https://robohash.org/ullamquivoluptatem.jpg?size=64x64&set=set1", "Granada"),
  (83, "Elnora Tincey", "https://robohash.org/autexpeditanon.jpg?size=64x64&set=set1", "Shitouhe"),
  (84, "Kalil Boow", "https://robohash.org/modieased.jpg?size=64x64&set=set1", "Borgustanskaya"),
  (85, "Klement Stockall", "https://robohash.org/aliquidetfugit.jpg?size=64x64&set=set1", "Pombal"),
  (86, "Mira Gadney", "https://robohash.org/exercitationemquisit.jpg?size=64x64&set=set1", "Bryukhovetskaya"),
  (87, "Gale Ralph", "https://robohash.org/idatquequis.jpg?size=64x64&set=set1", "Metchosin"),
  (88, "Edita Clue", "https://robohash.org/recusandaeetnon.jpg?size=64x64&set=set1", "Santo Domingo"),
  (89, "Willi Woffinden", "https://robohash.org/veritatiseiusculpa.jpg?size=64x64&set=set1", "Cerro Punta"),
  (90, "Blancha Kaszper", "https://robohash.org/delenitioccaecatiest.jpg?size=64x64&set=set1", "Xikou"),
  (91, "Aurthur Fassum", "https://robohash.org/dolorequonihil.jpg?size=64x64&set=set1", "Amahusu"),
  (92, "Hannah Wallen", "https://robohash.org/ealaboreesse.jpg?size=64x64&set=set1", "Borāzjān"),
  (93, "Andrei Glidden", "https://robohash.org/quibusdametodit.jpg?size=64x64&set=set1", "Boyarka"),
  (94, "Dave McIlrath", "https://robohash.org/essemodivelit.jpg?size=64x64&set=set1", "Duofudu"),
  (95, "Rudolfo Botly", "https://robohash.org/dictaquiaquia.jpg?size=64x64&set=set1", "Villefranche-sur-Mer"),
  (96, "Roi Andriesse", "https://robohash.org/quiquilaborum.jpg?size=64x64&set=set1", "Xianghe"),
  (97, "Stavro Staning", "https://robohash.org/autducimusid.jpg?size=64x64&set=set1", "Cardal"),
  (98, "Udale Dowsey", "https://robohash.org/sitestin.jpg?size=64x64&set=set1", "Kičevo"),
  (99, "Doralyn Burgin", "https://robohash.org/delectusvoluptatemiste.jpg?size=64x64&set=set1", "Muzhou"),
  (100, "Garald Piaggia", "https://robohash.org/quaevoluptatemillum.jpg?size=64x64&set=set1", "Ayapel")
;

INSERT INTO `people_colors` (`people_id`, `color`)
VALUES
  (1, "Aquamarine"),
  (1, "Violet"),
  (1, "Khaki"),
  (2, "Goldenrod"),
  (2, "Yellow"),
  (2, "Yellow"),
  (3, "Yellow"),
  (3, "Puce"),
  (3, "Indigo"),
  (4, "Teal"),
  (4, "Fuscia"),
  (4, "Mauv"),
  (5, "Violet"),
  (5, "Pink"),
  (5, "Aquamarine"),
  (6, "Green"),
  (6, "Orange"),
  (6, "Purple"),
  (7, "Turquoise"),
  (7, "Purple"),
  (7, "Pink"),
  (8, "Turquoise"),
  (8, "Mauv"),
  (8, "Indigo"),
  (9, "Purple"),
  (9, "Puce"),
  (9, "Pink"),
  (10, "Aquamarine"),
  (10, "Violet"),
  (10, "Red"),
  (11, "Crimson"),
  (11, "Violet"),
  (11, "Green"),
  (12, "Puce"),
  (12, "Fuscia"),
  (12, "Teal"),
  (13, "Orange"),
  (13, "Pink"),
  (13, "Turquoise"),
  (14, "Purple"),
  (14, "Puce"),
  (14, "Yellow"),
  (15, "Crimson"),
  (15, "Mauv"),
  (15, "Fuscia"),
  (16, "Indigo"),
  (16, "Khaki"),
  (16, "Indigo"),
  (17, "Red"),
  (17, "Mauv"),
  (17, "Violet"),
  (18, "Khaki"),
  (18, "Goldenrod"),
  (18, "Mauv"),
  (19, "Crimson"),
  (19, "Khaki"),
  (19, "Crimson"),
  (20, "Orange"),
  (20, "Mauv"),
  (20, "Blue"),
  (21, "Mauv"),
  (21, "Aquamarine"),
  (21, "Red"),
  (22, "Turquoise"),
  (22, "Violet"),
  (22, "Fuscia"),
  (23, "Indigo"),
  (23, "Teal"),
  (23, "Indigo"),
  (24, "Yellow"),
  (24, "Orange"),
  (24, "Crimson"),
  (25, "Crimson"),
  (25, "Fuscia"),
  (25, "Pink"),
  (26, "Blue"),
  (26, "Green"),
  (26, "Blue"),
  (27, "Maroon"),
  (27, "Teal"),
  (27, "Maroon"),
  (28, "Yellow"),
  (28, "Goldenrod"),
  (28, "Aquamarine"),
  (29, "Khaki"),
  (29, "Khaki"),
  (29, "Red"),
  (30, "Green"),
  (30, "Khaki"),
  (30, "Blue"),
  (31, "Fuscia"),
  (31, "Purple"),
  (31, "Teal"),
  (32, "Teal"),
  (32, "Khaki"),
  (32, "Maroon"),
  (33, "Maroon"),
  (33, "Crimson"),
  (33, "Crimson"),
  (34, "Crimson"),
  (34, "Green"),
  (34, "Violet"),
  (35, "Yellow"),
  (35, "Orange"),
  (35, "Khaki"),
  (36, "Crimson"),
  (36, "Turquoise"),
  (36, "Goldenrod"),
  (37, "Green"),
  (37, "Turquoise"),
  (37, "Violet"),
  (38, "Indigo"),
  (38, "Puce"),
  (38, "Violet"),
  (39, "Maroon"),
  (39, "Turquoise"),
  (39, "Indigo"),
  (40, "Orange"),
  (40, "Yellow"),
  (40, "Purple"),
  (41, "Goldenrod"),
  (41, "Teal"),
  (41, "Fuscia"),
  (42, "Pink"),
  (42, "Orange"),
  (42, "Red"),
  (43, "Turquoise"),
  (43, "Aquamarine"),
  (43, "Puce"),
  (44, "Pink"),
  (44, "Teal"),
  (44, "Khaki"),
  (45, "Fuscia"),
  (45, "Green"),
  (45, "Khaki"),
  (46, "Blue"),
  (46, "Aquamarine"),
  (46, "Red"),
  (47, "Pink"),
  (47, "Turquoise"),
  (47, "Teal"),
  (48, "Violet"),
  (48, "Puce"),
  (48, "Aquamarine"),
  (49, "Orange"),
  (49, "Violet"),
  (49, "Khaki"),
  (50, "Red"),
  (50, "Khaki"),
  (50, "Green"),
  (51, "Green"),
  (51, "Blue"),
  (51, "Violet"),
  (52, "Red"),
  (52, "Crimson"),
  (52, "Indigo"),
  (53, "Purple"),
  (53, "Maroon"),
  (53, "Blue"),
  (54, "Violet"),
  (54, "Purple"),
  (54, "Orange"),
  (55, "Turquoise"),
  (55, "Turquoise"),
  (55, "Crimson"),
  (56, "Turquoise"),
  (56, "Violet"),
  (56, "Khaki"),
  (57, "Orange"),
  (57, "Red"),
  (57, "Turquoise"),
  (58, "Maroon"),
  (58, "Goldenrod"),
  (58, "Pink"),
  (59, "Purple"),
  (59, "Purple"),
  (59, "Mauv"),
  (60, "Yellow"),
  (60, "Orange"),
  (60, "Puce"),
  (61, "Blue"),
  (61, "Goldenrod"),
  (61, "Purple"),
  (62, "Violet"),
  (62, "Goldenrod"),
  (62, "Aquamarine"),
  (63, "Red"),
  (63, "Purple"),
  (63, "Goldenrod"),
  (64, "Crimson"),
  (64, "Maroon"),
  (64, "Goldenrod"),
  (65, "Khaki"),
  (65, "Mauv"),
  (65, "Green"),
  (66, "Pink"),
  (66, "Green"),
  (66, "Teal"),
  (67, "Green"),
  (67, "Khaki"),
  (67, "Turquoise"),
  (68, "Aquamarine"),
  (68, "Goldenrod"),
  (68, "Violet"),
  (69, "Violet"),
  (69, "Turquoise"),
  (69, "Goldenrod"),
  (70, "Pink"),
  (70, "Orange"),
  (70, "Yellow"),
  (71, "Aquamarine"),
  (71, "Purple"),
  (71, "Violet"),
  (72, "Turquoise"),
  (72, "Mauv"),
  (72, "Violet"),
  (73, "Purple"),
  (73, "Orange"),
  (73, "Puce"),
  (74, "Mauv"),
  (74, "Khaki"),
  (74, "Aquamarine"),
  (75, "Pink"),
  (75, "Indigo"),
  (75, "Mauv"),
  (76, "Maroon"),
  (76, "Turquoise"),
  (76, "Khaki"),
  (77, "Red"),
  (77, "Violet"),
  (77, "Aquamarine"),
  (78, "Goldenrod"),
  (78, "Fuscia"),
  (78, "Khaki"),
  (79, "Pink"),
  (79, "Maroon"),
  (79, "Purple"),
  (80, "Maroon"),
  (80, "Fuscia"),
  (80, "Fuscia"),
  (81, "Fuscia"),
  (81, "Orange"),
  (81, "Khaki"),
  (82, "Puce"),
  (82, "Goldenrod"),
  (82, "Maroon"),
  (83, "Khaki"),
  (83, "Red"),
  (83, "Red"),
  (84, "Yellow"),
  (84, "Crimson"),
  (84, "Indigo"),
  (85, "Maroon"),
  (85, "Turquoise"),
  (85, "Goldenrod"),
  (86, "Red"),
  (86, "Crimson"),
  (86, "Aquamarine"),
  (87, "Teal"),
  (87, "Mauv"),
  (87, "Purple"),
  (88, "Crimson"),
  (88, "Maroon"),
  (88, "Orange"),
  (89, "Violet"),
  (89, "Crimson"),
  (89, "Crimson"),
  (90, "Violet"),
  (90, "Green"),
  (90, "Turquoise"),
  (91, "Puce"),
  (91, "Red"),
  (91, "Khaki"),
  (92, "Blue"),
  (92, "Teal"),
  (92, "Red"),
  (93, "Maroon"),
  (93, "Red"),
  (93, "Pink"),
  (94, "Aquamarine"),
  (94, "Violet"),
  (94, "Fuscia"),
  (95, "Khaki"),
  (95, "Mauv"),
  (95, "Orange"),
  (96, "Teal"),
  (96, "Pink"),
  (96, "Fuscia"),
  (97, "Aquamarine"),
  (97, "Blue"),
  (97, "Violet"),
  (98, "Goldenrod"),
  (98, "Yellow"),
  (98, "Teal"),
  (99, "Aquamarine"),
  (99, "Yellow"),
  (99, "Maroon"),
  (100, "Green"),
  (100, "Puce"),
  (100, "Red")
;
